# ═══════════════════════════════════════════════════════════════════════════════
#  Vera - build/run helper (Windows PowerShell)   generated by tools/scaffold.py
#  Usage: .\build.ps1 <command>
# ═══════════════════════════════════════════════════════════════════════════════
param([Parameter(Position=0)][string]$Command = "help")

$ErrorActionPreference = "Stop"
$RepoRoot = $PSScriptRoot
$Parent   = Split-Path $RepoRoot -Parent
$Py       = if ($env:PY) { $env:PY } else { "python" }
$Venv     = if ($env:VENV) { $env:VENV } else { ".venv" }
$Port     = if ($env:PORT) { $env:PORT } else { "8999" }
$Base     = "http://localhost:$Port"

function Get-Compose {
  docker compose version *> $null
  if ($LASTEXITCODE -eq 0) { return "docker compose" } else { return "docker-compose" }
}

function Show-Usage {
  @"
Vera build helper

  .\build.ps1 up         Start full docker stack (detached)
  .\build.ps1 build      Rebuild image and start
  .\build.ps1 down       Stop the stack
  .\build.ps1 logs       Follow orchestrator logs
  .\build.ps1 venv       Create .venv and install requirements
  .\build.ps1 run        Run orchestrator locally (no docker)
  .\build.ps1 secret     Print a fresh VERA_SECRET_KEY
  .\build.ps1 health     GET /health
  .\build.ps1 caps       List capabilities (GET /mcp/tools)
  .\build.ps1 tour       Terminal guided tour
  .\build.ps1 welcome    Open the HTML welcome guide
"@ | Write-Output
}

switch ($Command) {
  "up"      { Invoke-Expression "$(Get-Compose) up -d" }
  "build"   { Invoke-Expression "$(Get-Compose) up -d --build" }
  "down"    { Invoke-Expression "$(Get-Compose) down" }
  "logs"    { Invoke-Expression "$(Get-Compose) logs -f vera" }
  "venv"    { & $Py -m venv $Venv; & "$Venv\Scripts\pip.exe" install --upgrade pip; & "$Venv\Scripts\pip.exe" install -r requirements.txt }
  "run"     { $env:PYTHONPATH = $Parent; Push-Location $Parent; & $Py -m Vera.vera.capability_orchestration; Pop-Location }
  "secret"  { & $Py -c "from cryptography.fernet import Fernet;print(Fernet.generate_key().decode())" }
  "health"  { try { Invoke-RestMethod "$Base/health" | ConvertTo-Json -Depth 6 } catch { Write-Output "Vera not reachable at $Base" } }
  "caps"    { try { Invoke-RestMethod "$Base/mcp/tools" | ConvertTo-Json -Depth 6 } catch { Write-Output "Vera not reachable at $Base" } }
  "tour"    { & $Py welcome/welcome.py }
  "welcome" { & $Py -c "import webbrowser,pathlib;webbrowser.open(pathlib.Path('welcome/index.html').resolve().as_uri())" }
  default   { Show-Usage }
}
