#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
#  Vera — build/run helper (POSIX)   generated by tools/scaffold.py
#  Usage: ./build.sh <command>
# ═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT="$(dirname "$REPO_ROOT")"
PY="${PY:-python3}"
VENV="${VENV:-.venv}"
PORT="${PORT:-8999}"
BASE="http://localhost:$PORT"

if docker compose version >/dev/null 2>&1; then COMPOSE="docker compose"; else COMPOSE="docker-compose"; fi

usage() {
  cat <<EOF
Vera build helper

  ./build.sh up         Start full docker stack (detached)
  ./build.sh build      Rebuild image and start
  ./build.sh down       Stop the stack
  ./build.sh logs       Follow orchestrator logs
  ./build.sh venv       Create .venv and install requirements
  ./build.sh run        Run orchestrator locally (no docker)
  ./build.sh secret     Print a fresh VERA_SECRET_KEY
  ./build.sh health     Curl GET /health
  ./build.sh caps       List capabilities (GET /mcp/tools)
  ./build.sh tour       Terminal guided tour
  ./build.sh welcome    Open the HTML welcome guide
EOF
}

cmd="${1:-help}"
case "$cmd" in
  up)      $COMPOSE up -d ;;
  build)   $COMPOSE up -d --build ;;
  down)    $COMPOSE down ;;
  logs)    $COMPOSE logs -f vera ;;
  venv)    "$PY" -m venv "$VENV" && "$VENV/bin/pip" install --upgrade pip && "$VENV/bin/pip" install -r requirements.txt ;;
  run)     cd "$PARENT" && PYTHONPATH="$PARENT" "$PY" -m Vera.vera.capability_orchestration ;;
  secret)  "$PY" -c "from cryptography.fernet import Fernet;print(Fernet.generate_key().decode())" ;;
  health)  curl -sf "$BASE/health" | "$PY" -m json.tool || echo "Vera not reachable at $BASE" ;;
  caps)    curl -sf "$BASE/mcp/tools" | "$PY" -m json.tool || echo "Vera not reachable at $BASE" ;;
  tour)    "$PY" welcome/welcome.py ;;
  welcome) "$PY" -c "import webbrowser,pathlib;webbrowser.open(pathlib.Path('welcome/index.html').resolve().as_uri())" ;;
  help|*)  usage ;;
esac
