# ═══════════════════════════════════════════════════════════════════════════════
#  Vera — Makefile  (generated by tools/scaffold.py)
#  Run `make help` for the full target list.
# ═══════════════════════════════════════════════════════════════════════════════
.DEFAULT_GOAL := help
SHELL := /bin/bash

# Parent of the repo root must be importable so `Vera.vera...` resolves.
REPO_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
PARENT    := $(abspath $(REPO_ROOT)/..)
PY        ?= python3
VENV      ?= .venv
PORT      ?= 8999

# config.py is the single source of truth for TLS (it reads env + repo-root .env);
# ask it so health/caps/docs pick the right scheme and accept the self-signed cert.
TLS_ON    := $(shell cd $(PARENT) && PYTHONPATH=$(PARENT) $(PY) -c 'from Vera.vera.config import cfg; print(1 if cfg.TLS_ENABLED else 0)' 2>/dev/null || echo 0)
ifeq ($(TLS_ON),1)
BASE      ?= https://localhost:$(PORT)
CURL      := curl -skf
else
BASE      ?= http://localhost:$(PORT)
CURL      := curl -sf
endif

COMPOSE := $(shell if docker compose version >/dev/null 2>&1; then echo "docker compose"; else echo "docker-compose"; fi)

.PHONY: help
help:  ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

# ── Docker stack ───────────────────────────────────────────────────────────────
.PHONY: up
up:  ## Start the full stack in docker (detached)
	$(COMPOSE) up -d

.PHONY: build
build:  ## Rebuild the vera image and start
	$(COMPOSE) up -d --build

.PHONY: down
down:  ## Stop the stack
	$(COMPOSE) down

.PHONY: nuke
nuke:  ## Stop the stack AND delete volumes (DESTRUCTIVE)
	$(COMPOSE) down -v

.PHONY: logs
logs:  ## Follow orchestrator logs
	$(COMPOSE) logs -f vera

.PHONY: ps
ps:  ## Show stack status
	$(COMPOSE) ps

# ── Native (no docker) ─────────────────────────────────────────────────────────
.PHONY: venv
venv:  ## Create a local virtualenv and install requirements
	$(PY) -m venv $(VENV)
	$(VENV)/bin/pip install --upgrade pip
	$(VENV)/bin/pip install -r requirements.txt

.PHONY: run
run:  ## Run the orchestrator locally (python -m), reading .env if present
	cd $(PARENT) && PYTHONPATH=$(PARENT) $(PY) -m Vera.vera.capability_orchestration

.PHONY: secret
secret:  ## Print a fresh VERA_SECRET_KEY
	$(PY) -c "from cryptography.fernet import Fernet;print(Fernet.generate_key().decode())"

.PHONY: install-hooks
install-hooks:  ## Enable repo-hygiene git hooks (secret-scan + branch/author/message guardrails)
	git config core.hooksPath tools/hooks
	@echo "Hooks active: block main commits, typed branch names, no AI author/attribution, secret-scan."
	@echo "Bypass once (sparingly) with: git commit --no-verify"

.PHONY: scan
scan:  ## Scan all tracked files for leaked secrets
	$(PY) tools/secret_scan.py --all

# ── Verification & exploration ─────────────────────────────────────────────────
.PHONY: health
health:  ## Hit GET /health on the running orchestrator
	$(CURL) $(BASE)/health | $(PY) -m json.tool || echo "Vera not reachable at $(BASE)"

.PHONY: caps
caps:  ## List registered capabilities (GET /mcp/tools)
	$(CURL) $(BASE)/mcp/tools | $(PY) -m json.tool || echo "Vera not reachable at $(BASE)"

.PHONY: test
test:  ## Smoke-test the running orchestrator
	$(PY) welcome/welcome.py --check

.PHONY: test-unit
test-unit:  ## Run the pytest unit suite (operator + docgen contract)
	$(PY) -m pytest tests -q

.PHONY: test-critical
test-critical:  ## Run the critical-system regression tier (§6 gate set)
	$(PY) -m pytest tests -m critical -q

.PHONY: test-hooks
test-hooks:  ## Test the repo-hygiene git hooks (branch/author/message guardrails)
	sh tests/test_hooks.sh

.PHONY: docs-shots
docs-shots:  ## Capture UI screenshots + regenerate docs (needs requirements-operator.txt)
	$(PY) tools/vera-docgen/docgen.py run --base-url $(BASE)

.PHONY: notebook
notebook:  ## Launch the quickstart Jupyter notebook
	jupyter notebook notebooks/vera_quickstart.ipynb

.PHONY: tour
tour:  ## Run the terminal guided tour
	$(PY) welcome/welcome.py

.PHONY: welcome
welcome:  ## Open the HTML welcome guide in a browser
	$(PY) -c "import webbrowser,pathlib;webbrowser.open(pathlib.Path('welcome/index.html').resolve().as_uri())"

.PHONY: docs
docs:  ## Open the API docs (Swagger UI)
	$(PY) -c "import webbrowser;webbrowser.open('$(BASE)/docs')"
