// <vera-widget> / window.VeraWidget (UI redesign M2): every drawn form renders fixture data at M; XS and S are the
// compositions the Sizes board names; L adds the detail list and XL the table; an unknown form says so; both record
// shapes normalise to one; the shape rule and the fallback rule are the chat's, now here.
//   node tests/test_widget_element.cjs   (CommonJS: the pipeline's gate parses every js file as a script)
const fs = require('node:fs'); const path = require('node:path'); const vm = require('node:vm');
const here = __dirname;
const src = fs.readFileSync(path.join(here, '..', 'vera', 'widgets', 'widget_element.js'), 'utf8');
const defined = {};
const ctx = { window: {}, console, HTMLElement: class {}, CustomEvent: class {}, customElements: { get: (n) => defined[n], define: (n, c) => { defined[n] = c; } }, document: { querySelectorAll: () => [], createElement: () => ({ setAttribute() {}, appendChild() {} }) } };
ctx.window.customElements = ctx.customElements; ctx.window.document = ctx.document;
// the one projection library first (the element loads /ui/iso.js itself in a page; here it is in the context already)
vm.runInNewContext(fs.readFileSync(path.join(here, '..', 'vera', 'ui', 'iso.js'), 'utf8'), ctx);
vm.runInNewContext(src, ctx);
const W = ctx.window.VeraWidget;
let fails = 0; const t = (name, cond, extra) => { console.log((cond ? 'ok   ' : 'FAIL ') + name + (cond ? '' : '  ' + (extra || ''))); if (!cond) fails++; };

t('api', ['draw', 'forms', 'normalise', 'formByShape', 'dataFor', 'applyMap', 'pick', 'mapped', 'formFor', 'readable', 'key', 'hydrate', 'css', 'ensureCss', 'sample', 'call', 'ensureIso'].every((k) => typeof W[k] === 'function') && W.version === 4);
t('the element is defined', !!defined['vera-widget']);
const series = [{ t: 1, v: 40 }, { t: 2, v: 48 }, { t: 3, v: 62 }, { t: 4, v: 55 }];
const fix = {
  trace: [series, /<polyline/], radial: [{ value: 62, min: 0, max: 100 }, /62%<\/text>/], counter: [{ value: 1234, unit: 'ms', delta: -12 }, /vb-seg7[\s\S]*>1<[\s\S]*>4<[\s\S]*class="dn">-12/],
  bar: [{ value: 7, min: 0, max: 10, unit: 'G' }, /vw-meter[\s\S]*width:70\.0%/], bars: [{ a: 3, b: 9, c: 1 }, /<rect[\s\S]*<rect[\s\S]*<rect/], thermo: [{ cpu: 62, gpu: 31 }, /vw-therm[\s\S]*cpu/],
  heat: [Object.fromEntries('abcdefghij'.split('').map((k, i) => [k, i + 1])), /vb-heatstrip[\s\S]*grid-template-columns:repeat\(10,1fr\)/], matrix: [{ ct126: { api: 'ok', db: 'down' }, ct121: { api: 1, db: 0.5 } }, /vb-mxh[\s\S]*>api<[\s\S]*vb-mxr[\s\S]*ct126/],
  donut: [{ running: 26, paused: 3, stopped: 4 }, /vw-donut[\s\S]*running/], stack: [{ llm: 5, embed: 3 }, /vb-stackbar/], pills: [[{ name: 'redis', status: 'ok' }, { name: 'neo4j', status: 'down' }], /vb-pillw[\s\S]*redis[\s\S]*neo4j/],
  log: [[{ t: '2026-09-11T09:21:00', kind: 'INFO', text: 'pull skipped' }], /vb-log[\s\S]*09:21[\s\S]*pull skipped/], lane: [[{ t: 1, kind: 'a', text: 'x' }, { t: 2, kind: 'b', text: 'y' }], /vb-lane[\s\S]*<b>a<\/b><em>x<\/em>/],
  table: [[{ name: 'ct126', load: 0.6 }, { name: 'ct121', load: 0.2 }], /vb-dgr h[\s\S]*>name<span>[\s\S]*>load<span>[\s\S]*ct126/], files: [[{ path: '/a.py', size: 12 }], /vb-fr[\s\S]*a\.py/], list: [['one', 'two'], /vw-list[\s\S]*one/],
  checklist: [[{ text: 'gate', done: true }, { text: 'sweep' }], /vb-ck done"><i>✓<\/i>gate[\s\S]*vb-ck"><i><\/i>sweep/], stepper: [{ stages: [{ name: 'plan', done: true }, { name: 'act', current: true }, { name: 'verify' }] }, /done[\s\S]*now[\s\S]*verify/],
  calendar: [[{ when: '2026-09-11T16:00', title: 'sweep' }], /vb-cal[\s\S]*2026-09-11 · 1/], string: ['hello', /vw-str">hello/], kv: [{ ok: true, node: 'ct126' }, /vw-kv[\s\S]*node/],
  scatter: [[{ x: 1, y: 2 }, { x: 3, y: 4 }], /vb-scatter[\s\S]*left:6\.0%[\s\S]*left:94\.0%/], diagram: [{ nodes: [{ id: 'a' }, { id: 'b' }], links: [{ source: 'a', target: 'b' }] }, /vw-mm[\s\S]*data-mm-code="graph LR/], pipes: [{ nodes: [{ id: 'a' }, { id: 'b' }], links: [{ source: 'a', target: 'b' }] }, /vb-pipes[\s\S]*vb-isow[\s\S]*isoe flowe/],
};
let ok = true;
for (const [form, [data, re]] of Object.entries(fix)) { const h = W.draw(form, data, 'm'); if (!re.test(h) || /class="wempty"/.test(h)) { ok = false; console.log('  ' + form + ' → ' + h.slice(0, 160)); } }
t('every drawn form renders its fixture at M (' + Object.keys(fix).length + ' forms)', ok);
t('aliases resolve to a renderer', /<polyline/.test(W.draw('sparkline', series, 'm')) && /<polyline/.test(W.draw('line', series, 'm')) && /62%/.test(W.draw('ring', { value: 62, min: 0, max: 100 }, 'm')) && /vb-rw/.test(W.draw('ranked', { a: 1, b: 2 }, 'm')) && /vb-level/.test(W.draw('battery', { value: 3, max: 10 }, 'm')));
t('unknown form says so', /class="wempty">form zzz · no drawing yet/.test(W.draw('zzz', {}, 'm')));
t('no data draws the SAMPLE face, marked (sample:false draws the form\'s OWN empty state — what it says of nothing)', /data-sample="1"/.test(W.draw('trace', null, 'm')) && /<polyline/.test(W.draw('trace', null, 'm')) && /vw-sampletag/.test(W.draw('trace', null, 'm')) && /a trace needs two/.test(W.draw('trace', [1], 'm')) && /a trace needs two/.test(W.draw('trace', null, 'm', { sample: false })) && /wempty">no rows/.test(W.draw('table', [], 'm', { sample: false })) && /wempty">no rows/.test(W.draw('table', { ok: true, rows: [] }, 'm', { sample: false })) && /a feed needs stories/.test(W.draw('feed', [], 'm', { sample: false })) && !/data-sample/.test(W.draw('trace', series, 'm')) && !/data-sample/.test(W.draw('table', [], 'm', { sample: false })));
// ── the sample rule on a dashboard of real reads (the coordinator, 2026-09-13): never the sample after a read ──
const crd = { form: 'composite', layout: '2x2', children: [{ slot: 'a', record: { form: 'table', title: 'Clusters', source: 'proxmox.clusters' } }, { slot: 'b', record: { form: 'radial', title: 'Gate', source: 'obs.pending' } }, { slot: 'c', record: { form: 'trace', title: 'Latency', source: 'sysmon.history' } }] };
const rd0 = W.draw('composite', undefined, 'm', { record: crd, kids: { a: { __read: true, data: [] }, b: { __read: true, data: undefined, err: 'Failed to fetch' }, c: { __read: true, data: series, err: 'timeout' } } });
t('a composite child READ and empty draws its own empty state, tagged read · empty — not the sample', /data-slot="a"[\s\S]*?vw-kempty">read · empty[\s\S]*?wempty">no rows/.test(rd0) && !/data-slot="a"[^]*?data-sample/.test(rd0.split('data-slot="b"')[0]));
t('a composite child whose read FAILED with nothing before draws the empty state with the error; one with a last reading keeps it dimmed', /data-slot="b"[\s\S]*?vw-kerr" title="Failed to fetch">read failed/.test(rd0) && /a ring needs/.test(rd0.split('data-slot="b"')[1].split('data-slot="c"')[0]) && /class="vw-slot vw-stale" data-slot="c"[\s\S]*?vw-kerr" title="timeout">last reading[\s\S]*?<polyline/.test(rd0) && !/data-sample/.test(rd0));
t('a composite child never read still draws its sample, marked', /data-sample="1"/.test(W.draw('composite', undefined, 'm', { record: crd, kids: {} })) && /data-slot="a"[\s\S]*?data-sample="1"/.test(W.draw('composite', undefined, 'm', { record: crd, kids: { b: { __read: true, data: { value: 3, max: 10 } } } })));
t('the element\'s three states are in its render (never read → sample; read · empty → the form\'s empty state; failed → last reading dimmed)', /const sampled = !wasRead && !have && form !== 'panel' && form !== 'composite';/.test(src) && /have = this\._data !== undefined && !isEmpty\(dataFor\(dataM, form\)\)/.test(src) && /const readEmpty = wasRead && !have && !this\._err, stale = wasRead && !!this\._err && have;/.test(src) && /why = 'read · empty'/.test(src) && /' · last reading'/.test(src) && /data-stale="1"/.test(src) && /keep\(k\.slot, undefined, this\._err\)/.test(src));
t('readable: the queues\' routing log, the connections and the sources are quiet reads', W.readable('ollama.request_log') && W.readable('evolve.instances') && W.readable('widget.sources') && W.readable('obs.workers') && !W.readable('exec.code.run'));
const dict = { ok: true, workers: { w1: { host: 'ct126', state: 'busy', load: 0.6 }, w2: { host: 'ct121', state: 'idle', load: 0.1 } }, hosts: { ct126: 4, ct121: 2 } };
t('applyMap: rows ← <dict> lists the entries as rows keyed by name (a dict of numbers as name · value)', JSON.stringify(W.applyMap(dict, { rows: 'workers' }, 'items')) === JSON.stringify([{ name: 'w1', host: 'ct126', state: 'busy', load: 0.6 }, { name: 'w2', host: 'ct121', state: 'idle', load: 0.1 }]) && JSON.stringify(W.applyMap(dict, { rows: 'hosts' }, 'items')) === JSON.stringify([{ name: 'ct126', value: 4 }, { name: 'ct121', value: 2 }]) && /vb-dgr[\s\S]*w1[\s\S]*ct126/.test(W.draw('table', dict, 'm', { map: { rows: 'workers' } })));
t('XS is glyph + one figure (the Sizes board: a spark for a series, a ring for a level)', /^<span class="vw-xs"[\s\S]*<i class="vw-g"><svg class="sp"[\s\S]*<\/svg><\/i>55<\/span>$/.test(W.draw('trace', series, 'xs')) && /<i class="vw-g"><svg viewBox="0 0 16 16">[\s\S]*stroke-dasharray="23\.4 37\.7"/.test(W.draw('radial', { value: 62, min: 0, max: 100 }, 'xs')) && /class="th"><i style="height:100%"/.test(W.draw('thermo', { cpu: 62, gpu: 31 }, 'xs')) && /class="dot"/.test(W.draw('log', [{ t: 1, kind: 'ERR', text: 'x' }], 'xs')));
t('S is a chip with the label', /^<span class="vw-chip"[\s\S]*<b>62%<\/b><small>gate<\/small><\/span>$/.test(W.draw('radial', { value: 62, min: 0, max: 100 }, 's', { title: 'gate' })));
t('L adds the detail list', /vw-l[\s\S]*vw-therm[\s\S]*vw-detail[\s\S]*cpu/.test(W.draw('thermo', { cpu: 62, gpu: 31 }, 'l')));
t('XL adds the table', /vw-xl[\s\S]*vw-detail[\s\S]*vw-xltable[\s\S]*vb-dgr h[\s\S]*>name<span>[\s\S]*>value<span>/.test(W.draw('thermo', { cpu: 62, gpu: 31 }, 'xl')));
t('bare returns just the form at any size', !/vw-l|vw-xl/.test(W.draw('thermo', { cpu: 62 }, 'xl', { bare: true })));
t('the envelope is seen through', /<polyline/.test(W.draw('trace', { ok: true, history: series }, 'm')));
// the shape rule (the Formats board's table) and the fallback
t('formByShape', W.formByShape({ value: 3, max: 10 }) === 'radial' && W.formByShape({ value: 3 }) === 'counter' && W.formByShape(series) === 'trace' && W.formByShape([{ x: 1, y: 2 }]) === 'scatter' && W.formByShape({ a: 1, b: 2 }) === 'thermo' && W.formByShape(Object.fromEntries('abcdefghij'.split('').map((k) => [k, 1]))) === 'heat' && W.formByShape([{ t: 1, kind: 'x', text: 'y' }]) === 'log' && W.formByShape({ nodes: [], links: [] }) === 'pipes' && W.formByShape([{ name: 'a' }]) === 'table' && W.formByShape([{ path: 'p' }]) === 'files' && W.formByShape([{ text: 'x', done: true }]) === 'checklist' && W.formByShape({ stages: [] }) === 'stepper' && W.formByShape({ ok: true, items: series }) === 'trace' && W.formByShape({ ok: true, text: 'hi' }) === null);
t('formFor: the chosen form, else the shape, else kv', W.formFor({ form: 'trace' }, series) === 'trace' && W.formFor({ form: 'table' }, { cpu: 62, gpu: 31 }) === 'thermo' && W.formFor({ form: 'table' }, { ok: true, node: 'ct126' }) === 'kv' && W.formFor({ form: 'radial' }, undefined) === 'radial');
// the record in one shape
const a = W.normalise({ name: 'GPU + queue', form: 'meter', reads: { cap: 'sysmon.status', args: { node: 'ct126' }, every: '10s' }, draw: { form: 'meter', size: 'S', glow: 1 } });
const b = W.normalise({ title: 'GPU', form: 'trace', source: 'sysmon.history', window: '1h', size: 'l', refresh: '5s' });
const c = W.normalise({ name: 'Gate', form: 'meter', reads: { cap: 'obs.pending' }, draw: { form: 'radial', size: 'S' } });
t('normalise: the template shape draws draw.form, not the kind', c.form === 'radial' && c.frame.size === 's');
t('normalise: the template shape', a.form === 'meter' && a.source === 'sysmon.status' && a.read.args.node === 'ct126' && a.read.refresh === '10s' && a.frame.size === 's' && a.draw.glow === 1 && a.title === 'GPU + queue');
t('normalise: the short form', b.form === 'trace' && b.source === 'sysmon.history' && b.read.window === '1h' && b.read.args.window === '1h' && b.frame.size === 'l' && b.read.refresh === '5s');
t('normalise: a panel record', W.normalise({ form: 'panel', source: 'panel:system-monitor' }).panel === 'system-monitor');
t('key is form · source · args', W.key({ form: 'trace', source: 'obs.events', args: { window: '1h' } }) === 'trace obs.events {"window":"1h"}');
t('readable: quiet reads only', W.readable('obs.health') && W.readable('sysmon.history') && W.readable('jobs.list') && !W.readable('code.write') && !W.readable('exec.code.run') && !W.readable('canvas.create'));
t('hydrate is a no-op without the mermaid element', W.hydrate({ querySelectorAll: () => [{}] }) === 0);
t('css names the classes the markup uses', /\.wempty/.test(W.css()) && /\.vw-therm/.test(W.css()) && /\.vw-xl/.test(W.css()) && /\.vw-b\{--b-ac:var\(--ac,var\(--acc/.test(W.css()) && ['vb-fc', 'vb-dgr', 'vb-seg7', 'vb-batt', 'vb-cnd', 'vb-stepr', 'vb-tl', 'vb-kb', 'vb-ncard', 'vb-cmpr', 'vb-topo', 'vb-tmap', 'vb-waffle'].every((c) => W.css().indexOf('.' + c) >= 0));
t('forms() lists the drawn forms and the aliases', W.forms().some((f) => f.id === 'trace' && f.shape === 'series') && W.forms().some((f) => f.id === 'sparkline' && f.as === 'trace') && W.forms().length > 60);
// the context graph as a form: mini lanes at M (a lane per family, hollow where not injected, the relations), the full element's slot at XL
const cgd = { nodes: [{ id: 'v1', label: 'fabric.py', kind: 'chunk', score: 0.9 }, { id: 'm1', label: 'recall', kind: 'memory', score: 0.6, included: false }, { id: 's1', label: 'recall step', kind: 'step', score: 0.8 }], rels: [{ from: 'm1', to: 'v1', kind: 'mem' }] };
const cgm = W.draw('context_graph', cgd, 'm', { bare: true, height: 90, labels: true, layout: 'lanes' });
t('context_graph at M: three lanes, three members, one relation, the ghost hollow, labels', /vw-cg/.test(cgm) && (cgm.match(/border-top:1px dashed/g) || []).length === 3 && (cgm.match(/border-radius:50%/g) || []).length === 3 && /<line /.test(cgm) && /background:transparent/.test(cgm) && /fabric\.py/.test(cgm), cgm.slice(0, 200));
t('context_graph at XL: the slot the full element fills', /vw-cgfull/.test(W.draw('context_graph', cgd, 'xl', {})) && /data-cg=/.test(W.draw('context_graph', cgd, 'xl', {})));
t('context_graph is a drawn form of the graph shape', W.forms().some((f) => f.id === 'context_graph' && f.shape === 'graph' && f.drawn));
// ── the sample face (defects 18 · 19): every form has a face before it has read anything ──
const SHAPES = ['level', 'series', 'values', 'events', 'graph', 'items', 'stages', 'rate', 'parts', 'ohlcv', 'matrix', 'calendar', 'string', 'points', 'panel', 'composite'];
t('sample() gives every shape realistic data', SHAPES.every((s) => W.sample(s) != null) && W.sample('radial').value === 62 && W.sample('level').max === 10 && W.sample('series').length === 24 && Object.keys(W.sample('values')).length === 6 && W.sample('events').length === 6 && W.sample('graph').nodes.length >= 7 && W.sample('stages').stages.length === 5 && W.sample('ohlcv').length === 12 && typeof W.sample('string') === 'string' && W.sample('composite').children.length === 4);
t('sample(form) follows the form: files have paths, checklists are ticked, the context graph has rels', W.sample('files')[0].path === '/srv/vera/fabric.py' && W.sample('checklist')[0].done === true && W.sample('context_graph').rels.length === 5 && W.sample('tank').value === 742 && W.sample('meter').max === 100);
// the catalogue's every form id (widget_record.py's FORMS) draws a face with no data — none says "no drawing yet" or "no data yet"
const py = fs.readFileSync(path.join(here, '..', 'vera', 'widgets', 'widget_record.py'), 'utf8');
const ids = [...py.matchAll(/_F\("([a-z0-9_-]+)",/g)].map((m) => m[1]);
const faceless = ids.filter((id) => { const h = W.draw(id, undefined, 'm'); return /no drawing yet|no data yet|class="wempty"/.test(h) && id !== 'panel'; });
t('every catalogue form draws a face with no data (' + ids.length + ' forms)', ids.length > 90 && !faceless.length, faceless.join(' '));
const faces = ['meter', 'gauge', 'column', 'graph', 'pulse', 'heat', 'trace', 'thermo', 'donut'].map((id) => W.draw(id, undefined, 'm').replace(/data-sample="1"/, ''));
t('different forms draw DIFFERENT faces (defect 18: not one placeholder for everything)', new Set(faces).size === faces.length && /vb-meter/.test(faces[0]) && /vb-gauge[\s\S]*<path/.test(faces[1]) && /vb-colbars/.test(faces[2]) && /vb-topo/.test(faces[3]) && /vb-pulse/.test(faces[4]) && /vb-heat/.test(faces[5]));// ── the Widgets board's still forms: every one draws its OWN face from its sample, none two alike, none sampled twice ──
const STILL = ['feed', 'files', 'table', 'gallery', 'terminal', 'agenda', 'people', 'links', 'announcement', 'board', 'hero', 'gauge', 'carousel', 'small-multiples', 'ring', 'area', 'histogram', 'scatter', 'waterfall', 'treemap', 'heat', 'calendar', 'radar', 'gantt', 'flow', 'bullet', 'stacked-bar', 'threshold', 'column', 'graph', 'log', 'checklist', 'pills', 'numbers', 'lane', 'minigraph', 'ranked', 'meter', 'funnel', 'waffle', 'lollipop', 'box', 'slope', 'horizon', 'diverging', 'step', 'stepper', 'counter', 'level', 'candles', 'matrix', 'spark-table', 'rings', 'timeline', 'bump', 'dots', 'pareto', 'tabs', 'slider', 'node', 'glance', 'pipeline', 'compare'];
const own = STILL.map((f) => { const h = W.draw(f, W.sample(f), 'm', { title: f }); return [f, h, new RegExp('class="vw-b vb-' + f + '(?: |")').test(h) && !/class="wempty"|data-sample/.test(h)]; });
t('the Widgets board\'s ' + STILL.length + ' still forms each draw their own face from their own sample', own.every((x) => x[2]) && new Set(own.map((x) => x[1])).size === own.length, own.filter((x) => !x[2]).map((x) => x[0] + ' → ' + x[1].slice(0, 80)).join(' | '));
t('forms() reports them drawn in their own right', STILL.every((f) => W.forms().some((x) => x.id === f && x.drawn && !x.as)));
// the drawings are the board's: the table sorts by a column and pages, the feed pages, the tabs pick a measure, the slider moves the line
const tb = W.draw('table', W.sample('table'), 'm', { ui: { sort: 'temp', dir: -1, page: 0 } });
t('table: a sortable grid — the header is a sort button with its arrow, the rows follow, the foot says the order and the page', /vb-dgr h[\s\S]*class="on" data-vb-set="sort:temp" data-vb-set2="dir:1">temp<span>↓<\/span>/.test(tb) && /sorted by temp · high first/.test(tb) && /1–4 of 6/.test(tb) && tb.indexOf('ct126') < tb.indexOf('ct121'));
// ── the table family (defect 50): columns from read.map, rows per size, L's footer, XL's search; rows · cards · temps ──
const TR = W.sample('table'); const cnt = (h) => (h.match(/<div class="vb-dgr" /g) || []).length;
t('table: S is the count chip, M shows 4 rows, L 8 with the footer, XL the whole table paged at 12 with a search box', /<b>6 rows<\/b>/.test(W.draw('table', TR, 's')) && cnt(W.draw('table', TR, 'm')) === 4 && !/vb-dgf/.test(W.draw('table', TR.slice(0, 3), 'm')) && cnt(W.draw('table', TR, 'l')) === 6 && /vb-dgf[\s\S]*1–6 of 6/.test(W.draw('table', TR, 'l')) && !/vw-l|vw-detail/.test(W.draw('table', TR, 'l')) && /vb-tsearch[\s\S]*data-vb-input="q"/.test(W.draw('table', TR, 'xl')) && !/vw-xl|vw-xltable/.test(W.draw('table', TR, 'xl')));
t('table: the search filters the rows; a miss says so', cnt(W.draw('table', TR, 'xl', { ui: { q: 'ct1' } })) === 4 && /nothing matches "zz"/.test(W.draw('table', TR, 'xl', { ui: { q: 'zz' } })));
const wk = { ok: true, workers: { w1: { host: 'ct126', state: 'busy', load: 0.6, extra: 1 }, w2: { host: 'ct121', state: 'idle', load: 0.1, extra: 2 } } };
const wt = W.draw('table', wk, 'm', { record: { form: 'table', read: { map: { rows: 'workers', name: 'name', host: 'host', load: 'load', state: 'state' } } } });
t('table: the columns are read.map\'s renames in their order (the container and the shape\'s fields excluded); a status column carries its dot', /vb-dgr h[\s\S]*>name<span>[\s\S]*>host<span>[\s\S]*>load<span>[\s\S]*>state<span>/.test(wt) && !/>extra</.test(wt) && /<i class="st" style="background:var\(--b-ac3\)"><\/i>busy/.test(wt));
t('table: draw.columns next, else the envelope\'s keys', /vb-dgr h[\s\S]*>load<span>[\s\S]*>node<span>/.test(W.draw('table', TR, 'm', { draw: { columns: ['load', 'node'] } })) && /vb-dgr h[\s\S]*>node<span>[\s\S]*>load<span>[\s\S]*>temp<span>[\s\S]*>in flight<span>/.test(W.draw('table', TR, 'm')));
t('rows: the table without its header, the size\'s rows, "+ n more"', /class="vw-b vb-rows/.test(W.draw('rows', TR, 'm')) && !/vb-dgr h/.test(W.draw('rows', TR, 'm')) && cnt(W.draw('rows', TR, 'm')) === 4 && /\+ 2 more/.test(W.draw('rows', TR, 'm')) && /<b>6 rows<\/b>/.test(W.draw('rows', TR, 's')) && /wempty">no rows/.test(W.draw('rows', [], 'm', { sample: false })));
t('cards: a card per row with the name, two fields and the status dot', (W.draw('cards', W.sample('cards'), 'm').match(/class="vb-card"/g) || []).length === 4 && /vb-card"><i style="background:var\(--b-ac2\)"[^>]*><\/i><b>ct126<\/b><span><small>value<\/small>62/.test(W.draw('cards', W.sample('cards'), 'm')));
t('temps: the Temp list — named values as rows, hottest first, the bar to the max with the throttle mark, banded colours', /vb-temps[\s\S]*<span class="n" title="gpu V100">[\s\S]*<span class="n" title="cpu pkg">/.test(W.draw('temps', W.sample('temps'), 'm')) && /color:var\(--b-ac4\)">71°/.test(W.draw('temps', W.sample('temps'), 'm')) && /<em style="left:73\.7%"/.test(W.draw('temps', W.sample('temps'), 'm')) && (W.draw('temps', W.sample('temps'), 'm').match(/class="vb-rw"/g) || []).length === 4 && (W.draw('temps', W.sample('temps'), 'l').match(/class="vb-rw"/g) || []).length === 6);
t('rows · cards · temps are drawn in their own right (no longer aliases)', ['rows', 'cards', 'temps'].every((f) => W.forms().some((x) => x.id === f && !x.as)));
t('feed: one story at a time, a pager with a dot per story', /vb-fc[\s\S]*class="h">Nightly review/.test(W.draw('feed', W.sample('feed'), 'm', { ui: { page: 1 } })) && (W.draw('feed', W.sample('feed'), 'm').match(/data-vb-set="page:/g) || []).length === 6 && /2 \/ 4/.test(W.draw('feed', W.sample('feed'), 'm', { ui: { page: 1 } })));
t('tabs: one measure up front, the others as pips', /class="on" data-vb-set="tab:disk">disk/.test(W.draw('tabs', W.sample('tabs'), 'm', { ui: { tab: 'disk' } })) && /disk per row/.test(W.draw('tabs', W.sample('tabs'), 'm', { ui: { tab: 'disk' } })) && (W.draw('tabs', W.sample('tabs'), 'm').match(/class="pips"/g) || []).length === 5);
t('slider: the threshold from the UI state, the count of sensors over it', /value="60" data-vb-input="thr"/.test(W.draw('slider', W.sample('slider'), 'm', { ui: { thr: 60 } })) && /1 of 6 at or over 60°/.test(W.draw('slider', W.sample('slider'), 'm', { ui: { thr: 60 } })) && /2 of 6 at or over 50°/.test(W.draw('slider', W.sample('slider'), 'm', { ui: { thr: 50 } })));
t('hero: the big number, the delta, the area trend, peak · median', /vb-hero"><b>62<\/b><span class="u">%<\/span><span class="vb-lbl up">▲ 14/.test(W.draw('hero', W.sample('hero'), 'm')) && /<path d="M0,80/.test(W.draw('hero', W.sample('hero'), 'm')) && /peak \d+ · median \d+/.test(W.draw('hero', W.sample('hero'), 'm')));
t('counter: seven-segment digits with a ghost 8 behind each, the 24 tick bars', (W.draw('counter', W.sample('counter'), 'm').match(/data-g="8"/g) || []).length === 5 && (W.draw('counter', W.sample('counter'), 'm').match(/vb-tick[\s\S]*?<\/div>/)[0].match(/<i /g) || []).length === 24);
t('level: ten cells, seven held, the expiring one amber', (W.draw('level', W.sample('level'), 'm').match(/<i class="on"/g) || []).length === 6 && /<i class="on warn"/.test(W.draw('level', W.sample('level'), 'm')) && /<b>7<\/b><span class="u">\/ 10 held/.test(W.draw('level', W.sample('level'), 'm')));
t('candles: a wick and a body per bar, the up/down legend', (W.draw('candles', W.sample('candles'), 'm').match(/class="wk"/g) || []).length === 12 && /up \d+<\/span><span><i[^>]*><\/i>down \d+/.test(W.draw('candles', W.sample('candles'), 'm')));
t('calendar: twelve weeks of day cells, the caption counts', (W.draw('calendar', W.sample('calendar'), 'm').match(/<i style="background:color-mix/g) || []).length === 84 && /12 weeks · \d+ items/.test(W.draw('calendar', W.sample('calendar'), 'm')));
t('graph: layered nodes and rotated edges; flow runs left → right with thickness by value', (W.draw('graph', W.sample('graph'), 'm').match(/class="tn"/g) || []).length === 9 && (W.draw('graph', W.sample('graph'), 'm').match(/class="te"/g) || []).length === 8 && /class="fe"[^>]*height:8\.0px/.test(W.draw('flow', W.sample('flow'), 'm')));
t('funnel narrows, waffle counts cells, treemap sizes by share, pareto carries the cumulative line', /width:100%[\s\S]*width:89%[\s\S]*width:67%/.test(W.draw('funnel', W.sample('funnel'), 'm')) && (W.draw('waffle', W.sample('waffle'), 'm').match(/<i style/g) || []).length === 100 && /vb-tmap[\s\S]*llm/.test(W.draw('treemap', W.sample('treemap'), 'm')) && /<polyline points="6\.3,62\.0/.test(W.draw('pareto', W.sample('pareto'), 'm')));
t('the reply\'s thermo · trace · radial · donut · kv · string · list · scatter · pipes still draw as before', /vw-therm/.test(W.draw('thermo', { a: 1 }, 'm')) && /<polyline/.test(W.draw('trace', series, 'm')) && /62%<\/text>/.test(W.draw('radial', { value: 62, min: 0, max: 100 }, 'm')) && /vw-donut/.test(W.draw('donut', { a: 1, b: 2 }, 'm')) && /vw-kv/.test(W.draw('kv', { a: 1 }, 'm')) && /vw-list/.test(W.draw('list', ['a'], 'm')) && /vw-mm/.test(W.draw('pipes', { nodes: [{ id: 'a' }], links: [] }, 'm', { draw: { engine: 'mermaid' } })) && /vw-mm/.test(W.draw('diagram', { nodes: [{ id: 'a' }], links: [] }, 'm')));
// ── the WidgetsMotion and WidgetsIso boards: every moving and isometric form draws its OWN face on VeraISO ──
const MOTION = ['dial', 'stack', 'thermo', 'stacks', 'candles', 'conveyor', 'city', 'shelf', 'sweep', 'meter-panel', 'orbit', 'tank', 'turbine', 'scope', 'pulse', 'pipes', 'comet', 'terminal', 'table', 'files', 'feed', 'board', 'agenda', 'log', 'split-flap'];
const ISOB = ['library', 'pages', 'list', 'calendar', 'people', 'feed', 'board', 'files', 'approvals', 'wiki', 'form', 'notices', 'candles', 'devices', 'notebook', 'gallery', 'pipeline', 'datasets', 'hosts', 'containers', 'models', 'activity', 'sandboxes', 'frame', 'topology', 'column', 'heat', 'treemap', 'waffle', 'small-multiples', 'gantt', 'scatter', 'funnel', 'area'];
const TBL = ['table', 'rows', 'cards', 'temps'];
t('the table family draws its own faces from its samples', TBL.every((f) => { const h = W.draw(f, W.sample(f), 'm', { title: f }); return new RegExp('class="vw-b vb-' + f + '(?: |")').test(h) && !/wempty|data-sample/.test(h); }));
const isoDraw = (f) => W.draw(f, W.sample(f), 'm', { title: f, projection: 'iso', width: 276 });
const mo = MOTION.map((f) => { const h = isoDraw(f); return [f, h, /class="vw-b vb-/.test(h) && !/wempty|data-sample|loading the projection/.test(h)]; });
t('the WidgetsMotion board\'s ' + MOTION.length + ' forms each draw their own face (iso where the board is iso)', mo.every((x) => x[2]) && new Set(mo.map((x) => x[1])).size === mo.length, mo.filter((x) => !x[2]).map((x) => x[0] + ' → ' + x[1].slice(0, 90)).join(' | '));
const io = ISOB.map((f) => { const h = isoDraw(f); return [f, h, /vb-isow/.test(h) && /class="f [lrt]/.test(h) && !/wempty|data-sample|loading the projection/.test(h)]; });
t('the WidgetsIso board\'s ' + ISOB.length + ' forms each draw faces on the projection', io.every((x) => x[2]) && new Set(io.map((x) => x[1])).size === io.length, io.filter((x) => !x[2]).map((x) => x[0] + ' → ' + x[1].slice(0, 90)).join(' | '));
t('the projection picks the drawing: thermo flat is the reply\'s list, thermo iso is the tubes; a form with one projection ignores it', /vw-therm/.test(W.draw('thermo', { a: 1, b: 2 }, 'm')) && /vb-thermo vb-iso[\s\S]*vb-isow/.test(W.draw('thermo', { a: 1, b: 2 }, 'm', { record: { form: 'thermo', projection: 'iso' } })) && /vb-isow/.test(W.draw('dial', { value: 3, max: 10 }, 'm')) && /vb-hero/.test(W.draw('hero', { value: 3 }, 'm', { projection: 'iso' })));
t('the record carries its projection', W.normalise({ form: 'thermo', projection: 'iso' }).projection === 'iso' && W.normalise({ form: 'thermo', draw: { proj: 'iso' } }).projection === 'iso' && W.normalise({ form: 'thermo' }).projection === '');
t('the iso frame lays real markup on the plane: a terminal standing, a page lying, a panel as its iframe', /class="xif term"[\s\S]*transform:matrix\(/.test(W.draw('frame', W.sample('frame'), 'm')) && /xif-ln p"><span class="k">vera@ct126/.test(W.draw('frame', W.sample('frame'), 'm')) && /class="xif page"/.test(W.draw('frame', { kind: 'page', title: 'report', lines: ['Boot analysis'] }, 'm')) && /<iframe src="\/ui\/panel\/window\?id=system-monitor"/.test(W.draw('frame', { kind: 'panel', panel: 'system-monitor' }, 'm')));
t('motion forms carry their motion in the markup (a lamp, a wave, a belt, a sweep, a beam)', /class="f t lamp"|class="f [lrt] lamp"/.test(isoDraw('dial')) && /wave/.test(isoDraw('tank')) && /class="f [lrt] mv"/.test(isoDraw('conveyor')) && /class="beam"/.test(isoDraw('sweep')) && /class="beam"/.test(W.draw('scope', W.sample('scope'), 'm')) && /class="pr"/.test(W.draw('pulse', W.sample('pulse'), 'm')) && /ospin/.test(W.draw('orbit', W.sample('orbit'), 'm')) && /fanspin/.test(W.draw('turbine', W.sample('turbine'), 'm')) && /class="flap"/.test(W.draw('split-flap', W.sample('split-flap'), 'm')));
t('the stack keeps the chat-era parts bar for keyed numbers and draws the card stack for rows', /vb-stacked-bar/.test(W.draw('stack', { a: 1, b: 2 }, 'm')) && /vb-stack[\s\S]*vb-isow/.test(W.draw('stack', W.sample('stack'), 'm')));
t('without the projection library an iso form says so instead of failing', (() => { const iso = ctx.window.VeraISO; ctx.window.VeraISO = null; const h = W.draw('dial', { value: 3, max: 10 }, 'm'); ctx.window.VeraISO = iso; return /loading the projection/.test(h) && !/wempty/.test(h); })());
t('forms() flags the iso-capable forms', W.forms().some((f) => f.id === 'thermo' && f.iso) && W.forms().some((f) => f.id === 'dial' && f.iso) && W.forms().some((f) => f.id === 'hero' && !f.iso));
t('a form the palette is set on follows it (load: bands to ac2 · ac3 · ac4; mono; accent)', /var\(--b-ac4\)/.test(W.draw('column', [1, 2, 9], 'm', { draw: { palette: 'load' } })) && /color-mix\(in srgb,var\(--b-t1\)/.test(W.draw('ranked', { a: 1, b: 2 }, 'm', { draw: { palette: 'mono' } })) && !/--b-dv/.test(W.draw('ranked', { a: 1, b: 2 }, 'm', { draw: { palette: 'accent' } })));
t('a placeholder string handed to a numeric form draws the sample, not the complaint', /data-sample="1"/.test(W.draw('meter', 'no reading yet', 'm')) && /vb-meter/.test(W.draw('meter', 'no reading yet', 'm')) && /vw-str">hello/.test(W.draw('string', 'hello', 'm')));
t('the sample face at XS and S is marked with a class', /vw-xs vw-sampled" data-sample="1"/.test(W.draw('radial', null, 'xs')) && /vw-chip vw-sampled"/.test(W.draw('radial', null, 's')) && /62%/.test(W.draw('radial', null, 's')));
t('an empty result is no data: the sample face', /data-sample="1"/.test(W.draw('thermo', {}, 'm')) && /data-sample="1"/.test(W.draw('table', [], 'm')) && /data-sample="1"/.test(W.draw('trace', { ok: true, history: [] }, 'm')));
t('a composite without children draws the sample composite (four children)', (W.draw('composite', null, 'm', { record: { form: 'composite' } }).match(/class="vw-slot" data-slot/g) || []).length === 4 && /data-sample="1"/.test(W.draw('composite', null, 'm')));
// ── read.map: the source's envelope through the record's field mapping; read.range: the level's lo – hi ──
t('pick walks a dotted path with indices', W.pick({ a: { b: [1, { c: 7 }] } }, 'a.b[1].c') === 7 && W.pick({ h: [1, 2, 3] }, 'h[-1]') === 3 && W.pick({ x: 1 }, '$') && W.pick({ x: 1 }, 'nope.deeper') === undefined);
const env = { ok: true, gpu: { util: 71, cap: 100 }, data: { nodes: [{ hostname: 'ct126', load: 0.6, temp: 71 }, { hostname: 'ct121', load: 0.2, temp: 54 }] }, history: series };
t('applyMap: a level picks value/max by path', W.applyMap(env, { value: 'gpu.util', max: 'gpu.cap' }, 'level').value === 71 && W.applyMap(env, { value: 'gpu.util', max: 'gpu.cap' }, 'level').max === 100);
const rowsM = W.applyMap(env, { rows: 'data.nodes', name: 'hostname', value: 'load' }, 'items');
t('applyMap: items pick the rows and rename their fields', Array.isArray(rowsM) && rowsM.length === 2 && rowsM[0].name === 'ct126' && rowsM[0].value === 0.6 && rowsM[0].hostname === 'ct126');
t('applyMap: a series picks its list; values from rows become keyed', W.applyMap(env, { series: 'history' }, 'series') === series && /<rect[\s\S]*ct126/.test(W.draw('bars', env, 'm', { map: { values: 'data.nodes', name: 'hostname', value: 'temp' } })));
t('applyMap: a path that resolves to nothing leaves the data alone (the sample face survives a stale map)', W.applyMap(env, { value: 'nope.x' }, 'level') === env && /data-sample="1"/.test(W.draw('radial', undefined, 'm', { record: { form: 'radial', read: { map: { value: 'gpu.util' } } } })));
t('draw() honours the record\'s read.map', /71%<\/text>/.test(W.draw('radial', env, 'm', { record: { form: 'radial', read: { map: { value: 'gpu.util', max: 'gpu.cap' } } } })) && /<polyline/.test(W.draw('trace', { ok: true, samples: series }, 'm', { record: { form: 'trace', read: { map: { series: 'samples' } } } })));
t('draw() honours the record\'s read.range (the record\'s wins over the source\'s)', /width:50\.0%/.test(W.draw('bar', { value: 5, min: 0, max: 100 }, 'm', { record: { form: 'bar', read: { range: [0, 10] } } })));
const nm = W.normalise({ form: 'radial', source: 'obs.pending', read: { map: { value: 'v' }, range: [0, 20] }, frame: { size: 'm', motion: false, legend: true }, skin: 'pixel', subject: 'nodes.ct126' });
t('normalise carries read.map · read.range · frame.motion/legend · skin · subject', nm.read.map.value === 'v' && nm.read.range[1] === 20 && nm.frame.motion === false && nm.frame.legend === true && nm.skin === 'pixel' && nm.subject === 'nodes.ct126' && W.normalise({ form: 'radial' }).frame.motion === null && W.normalise({ form: 'radial' }).skin === 'inherit');
// ── the composite: every child an ordinary widget with its own record and its own read (opts.kids per slot) ──
const crec = { form: 'composite', layout: '2x2', children: [{ slot: 'a', record: { form: 'radial', title: 'Gate', source: 'obs.pending' } }, { slot: 'b', record: { form: 'trace', title: 'Latency', source: 'sysmon.history', read: { map: { series: 'history' } } } }] };
const ch = W.draw('composite', undefined, 'm', { record: crec, kids: { a: { value: 3, min: 0, max: 20 }, b: { ok: true, history: series } } });
t('a composite draws its children from what the element read per slot, through each child\'s own map', (ch.match(/class="vw-slot" data-slot/g) || []).length === 2 && /vw-slot-h">Gate<b>3<\/b>/.test(ch) && /<polyline/.test(ch) && !/data-sample/.test(ch) && /vw-comp-2x2/.test(ch));
t('a child with nothing read yet draws its sample face, marked', /data-sample="1"/.test(W.draw('composite', undefined, 'm', { record: crec, kids: {} })));
const rl = W.draw('composite', undefined, 'm', { record: Object.assign({}, crec, { layout: 'report' }), kids: { a: { value: 3, min: 0, max: 20 } } });
t('a report / rail composite draws its children as chips in rows', /vw-slot-row[\s\S]*class="k">Gate<\/span><span class="vw-chip"/.test(rl) && /vw-comp-report/.test(rl));
t('css names the sample tag', /\.vw-sampletag/.test(W.css()) && /\.vw-sampled/.test(W.css()));
// ── the one /mcp/call helper opens prod's envelope and a stand-in's ──
(async () => {
  const answers = [{ type: 'tool_result', tool_name: 'x', content: { ok: true, a: 1 } }, { result: { ok: true, b: 2 } }, { ok: true, c: 3 }];
  let i = 0; ctx.fetch = async () => ({ json: async () => answers[i++] });
  const r = [await W.call('', 'x'), await W.call('', 'x'), await W.call('', 'x')];
  t('call() opens {type:tool_result, content}, {result} and the bare object', r[0].a === 1 && r[1].b === 2 && r[2].c === 3);
  // ── the surface (window.VeraWidgetConfig): the API, its record shapes, the two context-graph entries ──
  const C = ctx.window.VeraWidgetConfig;
  t('VeraWidgetConfig: open/close, version 3, the packs, the two context-graph entries', C && typeof C.open === 'function' && typeof C.close === 'function' && C.version === 3 && C.packs.length === 5 && C.packs[0][0] === 'inherit' && C.packs[4][0] === 'pixel' && C.entries.length === 2 && C.entries[0].id === 'context_graph' && C.entries[0].size === 'm' && C.entries[1].size === 'xl' && /mini/.test(C.entries[0].n) && /full/.test(C.entries[1].n));
  const rf = C.recordFrom({ name: 'GPU + queue', form: 'meter', reads: { cap: 'sysmon.status', args: { node: 'ct126' }, every: '10s' }, draw: { form: 'meter', size: 'S' }, placed: ['LHM · Ops glance', 'dashboard'] }, 'lhm');
  t('recordFrom: a template becomes the sheet\'s record (source · read · frame · placement)', rf.form === 'meter' && rf.source === 'sysmon.status' && rf.read.args.node === 'ct126' && rf.read.refresh === '10s' && rf.frame.size === 's' && rf.frame.dive === true && rf.placement.join(',') === 'rail,dashboard' && rf.title === 'GPU + queue');
  const rf2 = C.recordFrom({ form: 'radial' }, 'canvas');
  t('recordFrom: into sets the placement default', rf2.placement.join(',') === 'canvas' && C.recordFrom({ form: 'radial' }, 'reply').placement[0] === 'chat' && C.recordFrom({ form: 'radial' }, 'lhm').placement[0] === 'rail');
  const ro = C.recordOut(Object.assign(rf2, { projection: 'iso', frame: Object.assign(rf2.frame, { dive: false }), read: Object.assign(rf2.read, { range: [0, 8] }) }));
  t('recordOut: the full shape both readers take (deep_dive + dive, place + placement, draw.proj, read.range)', ro.frame.deep_dive === false && ro.frame.dive === false && ro.place === 'canvas' && ro.placement[0] === 'canvas' && ro.draw.proj === 'iso' && Array.isArray(ro.actions) && ro.read && ro.read.args && ro.read.range[1] === 8 && !('range' in C.recordOut(C.recordFrom({ form: 'radial' })).read));
  const comp = C.recordFrom({ form: 'composite', layout: '2x2', children: [{ slot: 'a', form: 'radial', source: 'obs.pending', size: 's' }, { slot: 'b', record: { form: 'trace', source: 'sysmon.history' } }] });
  t('recordFrom: a composite\'s children are records', comp.children.length === 2 && comp.children[0].record.form === 'radial' && comp.children[0].record.source === 'obs.pending' && comp.children[1].record.form === 'trace' && comp.layout === '2x2');
  t('the element takes bare — the host draws the head (a dashboard tile drew its title and figure twice)', /static get observedAttributes\(\) \{ return \['record', 'size', 'base', 'template-id', 'bare'\]; \}/.test(src) && /const small = size === 'xs' \|\| size === 's' \|\| this\.hasAttribute\('bare'\);/.test(src));
  const c1 = W.draw('counter', { value: 2506 }, 'm');
  t('counter: the seven-segment figure follows the body it stands in (a 2×2 tile\'s figure was cut off)', /vb-seg7/.test(c1) && /\.vb-seg7 span\{[^}]*font-size:clamp\(18px, 68cqh, 34px\)/.test(src) && /\.vb-seg7\{[^}]*padding:2px 0/.test(src), c1.slice(0, 120));
  t('the widget body is a size container (the figures size by it)', /\.vw-body\{[^}]*container-type:size\}/.test(src) && /\.vw-hero b\{font-size:clamp\(16px, 62cqh, 26px\)/.test(src));
  const g1 = W.draw('gauge', { value: 62, min: 0, max: 100, unit: '%' }, 'm', { title: 'GPU' });
  t('gauge: a level-shaped object is ONE gauge (not value · min · max)', (g1.match(/class="vb-gg"/g) || []).length === 1 && /62/.test(g1), g1.slice(0, 200));
  t('gauge: a { name: number } object is still one gauge per name', (W.draw('gauge', { cpu: 40, mem: 71 }, 'm').match(/class="vb-gg"/g) || []).length === 2);
  console.log(fails ? fails + ' FAILED' : 'all passed');
  process.exit(fails ? 1 : 0);
})();

