// The Live operations page: widgets for every node, room for them, straight billboards, a widgets-only mode, bus risers.
//   node tests/test_ops_panel.cjs
const fs = require('fs'), path = require('path');
const R = path.join(__dirname, '..');
const H = fs.readFileSync(path.join(R, 'vera', 'estate', 'ops_panel.html'), 'utf8');
let fails = 0;
const t = (name, ok, why) => { console.log((ok ? 'ok   ' : 'FAIL ') + name + (ok ? '' : '  ' + (why || ''))); if (!ok) fails++; };
const KINDS = ['server', 'dial', 'tank', 'thermo', 'tower', 'crates', 'chip', 'mast', 'conveyor', 'stack'];
t('every widget kind in the picker is built from boxes with the map\'s own projection', KINDS.every((k) => H.includes("['" + k + "', ") && H.includes('    ' + k + ': (g, k, n) => {')));
t('a machine carries a server and its readings; the rail adds, sizes and removes one at a time; choices are kept', H.includes('function wdefaults(n){') && H.includes("st('server'); if (n.load != null) st('dial', .75);") && H.includes("else if (k === 'drop') S.wl[nid]") && H.includes("localStorage.setItem('vera:ops:widgets'"));
t('3D: a node with widgets gets room - lanes and rows widen with the widgets on its plane, a crowded cell is a grid of columns, a domain column is as wide as its widest cell', H.includes('const cellW = (pl) => (1.6 + 0.6 * Math.min(3, maxW[pl] || 0)) * SP;') && H.includes('const rowV = (pl) => (1.1 + 0.35 * Math.min(3, maxW[pl] || 0)) * SP;') && H.includes('const ROWCAP = 6, grid = {};') && H.includes('const domW = DOM.map('));
t('2D: a row every 40 px times the spread, a ladder up to twelve', H.includes('const bandNeed = (pl) => 60 + (ladder(pl) - 1) * 40 * SP') && H.includes("clamp(Math.ceil((cellMax[pl] || 1)), 5, S.view === '2d' ? 12 : 9)"));
t('billboards stand straight up from their pin (never pushed aside), lifted in screen px (up to 120) clear of the widgets and of each other', H.includes('.nd.bb{transform-origin:50% 100%;transform:translate(-50%,-100%) translateY(calc(var(--r,20) * var(--ui,1) * -1px))') && H.includes('.stem{position:absolute;width:calc(1.5px * var(--ui,1));height:calc(var(--r,20) * var(--ui,1) * 1px);transform:translate(-50%,-100%)') && H.includes('let raise = RAISE0; while (hit(raise) && raise < 120) raise += 8;') && H.includes('placed.some((b) => over(r, b))') && H.includes('chipAt[n.id] = { x: p.x, y: p.y, r: raise };') && !H.includes('cx = b.x0 - hw - 4'));
t('the Labels · Both · Widgets switch: widgets only draws no billboards and a widget names its node', H.includes('data-lbl="widgets"') && H.includes("if (S.lbl === 'widgets' && wspec(n).length) return;") && H.includes("(S.lbl === 'widgets' && i === 0 ?") && H.includes("S.widgets = S.lbl !== 'labels'"));
t('nothing is clipped: floors are svg polygons that overflow the plot, the width is fitted, a lattice taller or wider than the plot grows it and the stage scrolls', H.includes("'<svg class=\"floors-svg\" width=\"'") && H.includes('.floors-svg{position:absolute;left:0;top:0;overflow:visible') && H.includes('FLAT ? (H - AXIS - 2 * FITM) / (R.maxY - R.minY) : 1') && H.includes("plot.style.setProperty('--plot-minw', Math.ceil(lay.G.width) + 'px');"));
t('between planes a pipe leaves by its plane\'s bus point, rises on a riser outside every plate and wears its origin plane\'s colour', H.includes('const vBusOf = (pl) => (FLAT ? VHof[pl] : VMAX) + 0.45 * SP;') && H.includes('return [P(A.u, A.v, A.z), P(A.u, A.vb, A.z), P(uR, A.vb, A.z), P(uR, A.vb, B.z), P(B.u, B.vb, B.z), P(B.u, B.v, B.z)];') && H.includes("const lc = ID[l.a].plane !== ID[l.b].plane ? PCOL[ID[l.a].plane] : LCOL[l.kind];") && H.includes("'<span class=\"bus\" style=\"left:'"));
t('zoom: the chrome counter-scales between 0.8 and 1.35, the widgets keep their size; the wheel zooms about the pointer', H.includes('const UI_MIN = 0.8, UI_MAX = 1.35;') && H.includes("v.style.setProperty('--ui', uiScale(S.vz).toFixed(3));") && H.includes('S.vx = mx - (mx - S.vx) * (z1 / z0);'));
t('the faces are one svg; the poll is fingerprinted and spares a focused input; rotation redraws the plot alone', H.includes('const polyOf = (q) =>') && H.includes('if (S.snap && fp === S.fp){ S.busy = false;') && H.includes('render({ plotOnly: true })'));
t('ctrl + drag rotates; the deep dive reads the estate record and the node\'s reading', H.includes("const rot = (e.ctrlKey || e.metaKey) && S.view === '3d';") && H.includes("'/estate/entity/resolve?ref='") && H.includes('function tree(v, depth, budget){'));
t('widget captions clear each other front to back: one that meets another steps down a line, else stays in the tooltip', H.includes('wd.labels.slice().sort((a, b) => b.y - a.y).forEach((l) =>') && H.includes('if (!capPlaced.some((b) =>'));
t('the page draws the estate it last saw at once (sessionStorage), asks again soon when the answer was served while a fresh one is gathered, and names each reader\'s time', H.includes("sessionStorage.setItem('vera:ops:last', JSON.stringify(c));") && H.includes("const last = JSON.parse(sessionStorage.getItem('vera:ops:last') || 'null');") && H.includes('if (c.refreshing && !S.soon)') && H.includes('const tm = snap.timing || {};'));
const C = fs.readFileSync(path.join(R, 'vera', 'estate', 'ops_capabilities.py'), 'utf8');
t('ops.snapshot is stale-while-revalidate: the last snapshot answers at once, a fresh one is gathered in the background, only a cold start or a refresh waits', C.includes('def _start_gather()') && C.includes('if have and not refresh:') && C.includes('return dict(_cache["out"], cached=True, age_s=round(age, 1), refreshing=_cache["inflight"] is not None)') && C.includes('out["timing"] = dict(sorted('));
console.log(fails ? fails + ' FAILED' : 'all passed');
process.exit(fails ? 1 : 0);
