// Notes/42 defects 52 · 53. 52: the mermaid element draws in the live theme's tokens and re-draws on a theme change,
// and sizes to its width (the height follows the drawing) — in the chat's slot and in the canvas item, whose slot takes
// the diagram's height up to its size's ceiling; the reply lands a diagram at m; an item the turn in view made opens in
// Hover and Zen. 53: the relevance pass answers only, the chat recalls, nothing parks by relevance, the turns counted
// are the exchanges; in Zen an out-of-focus item dims and folds instead of vanishing. The pure parts and the source.
//   node tests/test_canvas_diagram_stays.cjs
const path = require('node:path'); const fs = require('node:fs');
const R = (...p) => path.join(__dirname, '..', ...p);
const V = require(R('vera', 'canvas', 'canvas_element.js')); const SRC = fs.readFileSync(R('vera', 'canvas', 'canvas_element.js'), 'utf8');
const MM = fs.readFileSync(R('vera', 'render', 'vera_mermaid.js'), 'utf8'); const HTML = fs.readFileSync(R('vera', 'chat', 'chat_panel.html'), 'utf8');
let fails = 0; const t = (name, cond, extra) => { console.log((cond ? 'ok   ' : 'FAIL ') + name + (cond ? '' : '  ' + (extra || ''))); if (!cond) fails++; };
t('foldOf is exported (version 6)', typeof V.foldOf === 'function' && V.version === 6);

// ── 52 · the mermaid element ──
t('the theme is the live tokens first (--s1/--s2/--t1/--t2/--ac/--bd…), the older vars next, read at render time', MM.includes("bg:    v(['--s1', '--bg1', '--bg0'], '#101012')") && MM.includes("card:  v(['--s2', '--bg2'], '#1a1c20')") && MM.includes("text:  v(['--t1', '--text', '--fg'], '#d8dce4')") && MM.includes("acc:   v(['--ac', '--acc'], '#5a9e8f')") && MM.includes("line:  v(['--t2', '--dim2', '--bd2', '--border2'], '#8a92a0')")   /* the edges read the dim TEXT token, not the panel border: they were faint against the words (defect 76) */ && MM.includes("const t = this._theme(); this._held = false;") && MM.includes("const t2 = this._theme();"));
t('an element\'s themeVariables override the tokens (property and attribute); VeraMermaid.theme() answers the set', MM.includes("if (overrides && typeof overrides === 'object') for (const k of Object.keys(t)) if (overrides[k]) t[k] = String(overrides[k]);") && MM.includes("set themeVariables(v) {") && MM.includes("if (name === 'theme-variables') {") && MM.includes("static theme() { return THEME(); }"));
t('every connected element re-draws on a theme change: <html> data-theme/data-style observed, the vera:theme message heard', MM.includes("new MutationObserver(rethemeAll).observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme', 'data-style', 'data-den', 'data-blocks', 'class'] })") && MM.includes("d.type === 'vera:theme') rethemeAll();") && MM.includes("LIVE.add(this);") && MM.includes("disconnectedCallback() { LIVE.delete(this); }") && MM.includes("retheme() { if (!this._code || !this._svgEl) return;"));
t('the viewport takes the drawing\'s height at its width (aspect kept, ≤1.25×, ≥80), up to max-height 720; [fill] keeps its box', MM.includes("naturalHeight(width) { const b = this._bounds; if (!b || !b.w || !this._svgEl) return 0;") && MM.includes("const k = Math.min(w / b.w, 1.25); return Math.max(80, Math.round(b.h * k)); }") && MM.includes(".vp{position:relative;overflow:hidden;flex:1 1 auto;min-height:80px;") && MM.includes(":host([fill]) .vp{flex:1 1 0%;height:auto;min-height:0}") && MM.includes("const maxH = parseInt(this.getAttribute('max-height') || '720', 10) || 720;") && MM.includes("if (!this.style.height && !this.hasAttribute('fill')) this._vp.style.height = Math.min(maxH, natural) + 'px';") && !MM.includes("|| '460'"));
t('a width change sizes and fits again unless a pan or a zoom is held; vm:rendered carries width · height · natural', MM.includes("if (w && w !== lastW) { lastW = w; this._size(); } if (this._held) this._apply(); else this.fit();") && MM.includes("this._held = true;\n        this._vp.classList.add('panning');") && MM.includes("width: this._vp.clientWidth || 0, height: this._vp.clientHeight || 0, natural }"));

// ── 52 · the canvas item ──
t('the diagram slot\'s height is the diagram\'s own (--dh) up to the size\'s ceiling — s 120 · m 400 · l 640 · xl none; the body has no ceiling of its own', SRC.includes(".vc-diag .vc-live{height:var(--dh,150px);max-height:400px}.it[data-size=\"s\"] .vc-diag .vc-live{max-height:120px}.it[data-size=\"l\"] .vc-diag .vc-live{max-height:640px}.it[data-size=\"xl\"] .vc-diag .vc-live{max-height:none}") && SRC.includes(".it[data-type=\"diagram\"] .it-bd{max-height:none}") && !SRC.includes(".vc-diag .vc-live{height:150px}"));
t('the live diagram tells its height (vm:rendered → naturalHeight at the slot\'s width); the slot follows, the layer and the stage too', SRC.includes("inner.addEventListener('vm:rendered', () => this._diagramGrew(key, inner)); this._mermaidInto(inner, key); }") && SRC.includes("_diagramGrew(key, inner) {") && SRC.includes("const w = h.getBoundingClientRect().width || 300; const nat = inner.naturalHeight(w); if (!nat) return;") && SRC.includes("h.style.setProperty('--dh', dh); h.dataset.natural = String(Math.round(nat));") && SRC.includes("requestAnimationFrame(() => { this._liveLayout(); if (this.hasAttribute('stage')) this._placeNow(); });"));
// the mirror, one turn after the model placed a gauge: the band read "1 NOW · 1 IN FOCUS" and the item's classes read
// 'inf foldable compact' — in focus and folded at once; the focus set now keeps an item open in every tier
t('an item the relevance pass holds in focus never folds', V.foldOf({ tier: 'zen', inFocus: true }) === false && V.foldOf({ tier: 'hover', inFocus: true }) === false && V.foldOf({ tier: 'full', aged: true, inFocus: true }) === false && V.foldOf({ tier: 'hover', hasFocus: true, inFocus: false }) === true && SRC.includes('inFocus: !!F && F.has(key)'));
t('an item the turn in view produced opens in every tier (fresh); older ones fold as before', V.foldOf({ tier: 'zen', fresh: true }) === false && V.foldOf({ tier: 'hover', fresh: true }) === false && V.foldOf({ tier: 'zen', hasFocus: true, inFocus: false }) === true && V.foldOf({ tier: 'full', aged: true }) === true && V.foldOf({ tier: 'full' }) === false && V.foldOf({ tier: 'zen', open: true }) === false && SRC.includes("const fresh = !!mid && mid === focusMid;") && SRC.includes("foldOf({ tier, aged, open, now: isNow, fresh, hasFocus: !!F, inFocus: !!F && F.has(key) })"));
t('the reply lands a diagram at m (its height follows the drawing), a widget at its record\'s size, a table and an image at m, the rest at s', HTML.includes("size:_cvLandSize(m), anchor:{mid, turn:mid, from:(w&&w.dataset&&w.dataset.mid)||mid}") && HTML.includes("function _cvLandSize(m){") && HTML.includes("if(k==='diagram'||k==='table'||k==='image') return 'm';") && HTML.includes("return ['s','m','l','xl'].includes(s)?s:'m'; }") && !HTML.includes("content:m.content, key, at:'now', size:'s'"));
t('a lifted diagram is whole (the store has no cap; the 8000-char cut is gone)', HTML.includes("mermaid:s.slice(0,24000)") && !HTML.includes("mermaid:s.slice(0,8000)") && !HTML.includes("mermaid:src.slice(0,8000)"));

// ── 53 · the item the model placed stays ──
t('the relevance pass answers only (apply:false) — nothing parks by relevance', HTML.includes("recent, apply:false});") && !HTML.includes("apply:o.apply!==false"));
t('the turns it counts are the exchanges (the user turns — the anchors\' mids)', HTML.includes("querySelectorAll('#msgs .mwrap.u[data-mid]')"));
t('a parked item in focus is recalled through the resolver (canvas.add by key, anchored to the turn as recalled); the column repaints when one came back', HTML.includes("async function _cvRecall(cv, focus, mid){") && HTML.includes("filter(b=>b&&b.key&&b.state==='parked')") && HTML.includes("_capCall('canvas.add', Object.assign({session_id:SID, key:String(key)}, mid?{anchor:{mid, turn:mid, role:'recalled'}}:{}))") && HTML.includes("recalled=await _cvRecall(cv, r.focus||[], mid); if(recalled){ cv._rev=null; cv.refresh(); }"));
t('in Zen an out-of-focus item dims and folds — it is never removed', SRC.includes(".it.out{opacity:.45;transition:opacity .15s}.it.out:hover{opacity:1}") && !SRC.includes(".it.out{display:none}"));

t('the column learns the turn in focus from the transcript itself (the user turn a reply in view belongs to), not only from the graph page', HTML.includes("if((cv.dataset.focusMid||'')!==fm) cv.dataset.focusMid=fm; }catch(_){}") && HTML.includes("if(fw&&fw.classList.contains('a')){ let p=fw.previousElementSibling;"));
t('a diagram measured while folded (a zero box) is drawn again once it has one', MM.includes("this._blind = !(bb.width > 0 && bb.height > 0);") && MM.includes("if (w && this._blind && this._code) { this.render(this._code); lastW = w; return; }"));
t("a re-rendered slot (new markup on every revision) gets the drawn diagram's height again from the mount", SRC.includes("this._mermaidInto(el.firstChild, key); this._diagramGrew(key, el.firstChild);"));
console.log(fails ? fails + ' failed' : 'passed all checks'); process.exit(fails ? 1 : 0);
