// The Live operations page: every node kind has an iso widget, the floors move apart and spread, ctrl + drag rotates,
// the widget rail edits what stands on the planes, and a node's deep dive reads the estate's record and its own reading.
//   node tests/test_ops_panel.cjs
const fs = require('fs'), path = require('path');
const R = path.join(__dirname, '..');
const H = fs.readFileSync(path.join(R, 'vera', 'estate', 'ops_panel.html'), 'utf8');
let fails = 0;
const t = (name, ok, why) => { console.log((ok ? 'ok   ' : 'FAIL ') + name + (ok ? '' : '  ' + (why || ''))); if (!ok) fails++; };
const KINDS = ['server', 'dial', 'tank', 'thermo', 'tower', 'crates', 'chip', 'mast', 'conveyor', 'stack'];
t('every widget kind in the picker is built from boxes with the map\'s own projection', KINDS.every((k) => H.includes("['" + k + "', ") && H.includes('    ' + k + ': (g, k, n) => {')), KINDS.filter((k) => !H.includes('    ' + k + ': (g, k, n) => {')).join(' '));
t('a node carries SEVERAL widgets: a server for a machine and its readings (dial, thermometer, tank), each at its own place beside the pin; the rail adds, sizes and removes one at a time', H.includes('function wdefaults(n){') && H.includes("st('server'); if (n.load != null) st('dial', .75); if (n.temp != null) st('thermo', .75); if (n.disk_pct != null) st('tank', .75);") && H.includes('const OFFS = [[0.5, -0.1], [0.5, 0.5], [0.95, 0.2]') && H.includes("wspec(n).forEach((w, i) => { const off = OFFS[i % OFFS.length];") && H.includes("else if (k === 'drop') S.wl[nid] = { off: false, items: w.items.filter((_, i) => i !== idx) };") && H.includes("localStorage.setItem('vera:ops:widgets'"));
t('the server widget: a chassis on rails, four drive bays lit by the load, a power lamp for the state, a taller unit with a second layer for a VM', H.includes("const vm = n.type === 'qemu', Wd = 3.0, Dd = 1.6, Hh = vm ? 1.15 : 0.78") && H.includes('// drive bays on the front') && H.includes('// the power lamp') && H.includes("// the hypervisor's layer"));
t('zooming scales the widgets but not the chrome: chips, labels, pins, lines and cards counter-scale through --ui, held between a floor and a ceiling; the wheel zooms about the pointer', H.includes('const UI_MIN = 0.8, UI_MAX = 1.35;') && H.includes('const uiScale = (vz) => clamp(vz, UI_MIN, UI_MAX) / vz;') && H.includes("v.style.setProperty('--ui', uiScale(S.vz).toFixed(3));") && H.includes('.nd{position:absolute;transform:translate(-50%,-50%) scale(calc(var(--nsc,1) * var(--ui,1)))') && H.includes('.ndw{position:absolute;transform:translate(-50%,-50%) scale(var(--ui,1))') && H.includes('.plabel{') && H.includes('transform:scale(var(--ui,1));transform-origin:0 0}') && H.includes('.link{position:absolute;height:calc(2px * var(--ui,1))') && H.includes('S.vx = mx - (mx - S.vx) * (z1 / z0);'));
t('2D bands are as tall as their ladder asks (a row every 30 px times the spread) and the stage scrolls; the spread slider works in 2D too', H.includes('const bandNeed = (pl) => 52 + (ladder(pl) - 1) * 30 * SP') && H.includes("(is3d ? 26 : 30 * S.spread)") && H.includes("['segGap', 'segWsz'].forEach((id) => { $(id).hidden = !is3d; });"));
t('the gap slider moves the floors apart and the spread slider the lanes and rows of a floor; both are kept between visits', H.includes('id="rGap"') && H.includes('id="rSpread"') && H.includes('* S.zgap;') && H.includes('const VS = 1.0 * SP, TH = TILT') && H.includes("localStorage.setItem('vera:ops:view'"));
t('a floor is as deep as its fullest cell (a ladder of five to nine rows) and the flat grid lays floors out by their own sizes', H.includes("const ladder = (pl) => clamp(Math.ceil((cellMax[pl] || 1)), 5, S.view === '2d' ? 12 : 9);") && H.includes('VHof[p.id] = ((ladder(p.id) - 1) / 2) * VS + 0.45 * SP;') && H.includes('vOff[p.id] = v + (rowsD[r] - VHof[p.id]);'));
t('ctrl (or cmd) + drag rotates the 3D view - azimuth with x, tilt with y - and plain drag pans', H.includes("const rot = (e.ctrlKey || e.metaKey) && S.view === '3d';") && H.includes("S.azim = clamp(d.a0 + (e.clientX - d.x0) * 0.22, 26, 64); S.tilt = clamp(d.t0 - (e.clientY - d.y0) * 0.18, 4, 60);") && H.includes('<b>Ctrl + drag</b> rotates the view'));
t('the widget rail lists each plane\'s widgets with a size step, a remove and a picker; ⊕ on a node picks a kind beside it', H.includes('function renderRail(){') && H.includes('data-wsz-node=') && H.includes('data-woff=') && H.includes('data-wadd=') && H.includes('class="wpk"') && H.includes('data-asg='));
t('the deep dive reads estate.entity.resolve for a node with a reference and the node\'s own reading, drawn as a tree with the estate\'s planes, related things and the drawer', H.includes("'/estate/entity/resolve?ref='") && H.includes('function tree(v, depth, budget){') && H.includes('function slice(n, ans){') && H.includes('data-drawer=') && H.includes('<script src="/ui/vera-entity-drawer.js"></script>') && H.includes("<h3>Deep dive"));
t('restart on a docker host opens its containers in the estate rather than pretending', H.includes("if (n.kind === 'docker'){ if (window.veraUI && window.veraUI.openPlace) window.veraUI.openPlace('estate/docker'); return; }"));
t('the widgets\' faces are one svg layer of polygons (three thousand clipped divs froze a grown estate)', H.includes('const polyOf = (q) =>') && H.includes("parts.push('<svg class=\"owf-svg\" width=\"' + W + '\" height=\"' + H + '\">' + wd.faces.map(polyOf).join('') + '</svg>');") && !H.includes('<i class="owf '));
t('the poll redraws only when the estate changed, every ten seconds, never while an input has focus; the inspector stands while you type; a rotation redraws the plot alone', H.includes("if (S.snap && fp === S.fp){ S.busy = false; return; }") && H.includes("}, 10000);") && H.includes("const ae = document.activeElement; if (ae && insp.contains(ae) && ae.matches && ae.matches('input,textarea')) return;") && H.includes("render({ plotOnly: true })") && H.includes('if (!opts.plotOnly) renderInspector();'));
t('a 2D cell of twenty nodes gets a ladder of twelve rows', H.includes("clamp(Math.ceil((cellMax[pl] || 1)), 5, S.view === '2d' ? 12 : 9)"));
console.log(fails ? fails + ' FAILED' : 'all passed');
process.exit(fails ? 1 : 0);
