// the must-keep list vs the design. Reads Notes/39 (graph inventory + keep list) and Notes/40
// (widgets, workstreams) from the Vera repo and the boards' text, writes adopt-checklist.md with
// one row per must-keep item: keep / replaced-by / dropped (dropped needs the user's word).
//   node checklist.mjs <design dir> <vera repo> [out.md]
import fs from 'node:fs';
import path from 'node:path';
const [D, R, OUT = path.join(process.argv[2], 'adopt-checklist.md')] = process.argv.slice(2);
const read = (p) => fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
const n39 = read(path.join(R, 'Notes', '39-graph-inventory.md')), n40 = read(path.join(R, 'Notes', '40-implementation-scope.md'));
// keep items: table rows / list lines under a heading containing "keep" or "must"
const items = [];
const harvest = (txt, src) => {
  let on = false;
  for (const line of txt.split(/\r?\n/)){
    if (/^#{2,4}\s/.test(line)) on = /keep|must|widget|inventory/i.test(line);
    if (!on) continue;
    const m = line.match(/^\s*(?:[-*]|\d+\.|\|)\s*([^|\n]{6,160})/);
    if (m && !/^-{3,}/.test(m[1]) && !/^\s*(#|item|element)\s*\|/i.test(line)) items.push({ src, text:m[1].trim().replace(/\*\*/g, '') });
  }
};
harvest(n39, 'Notes/39'); harvest(n40, 'Notes/40');
// the design's text, for a cheap "mentioned" signal
const boards = fs.readdirSync(D).filter((f) => f.endsWith('.dc.html'));
const corpus = boards.map((f) => ({ f, t:fs.readFileSync(path.join(D, f), 'utf8').toLowerCase() }));
const rows = items.map((it) => {
  const key = it.text.toLowerCase().split(/[^a-z0-9.]+/).filter((w) => w.length > 3).slice(0, 4);
  const where = corpus.filter((c) => key.length && key.every((k) => c.t.includes(k))).map((c) => c.f.replace('.dc.html', ''));
  return `| ${it.src} | ${it.text.replace(/\|/g, '/')} | ${where.length ? 'keep · shown in ' + where.join(', ') : 'keep · NOT SHOWN — confirm it survives'} |`;
});
const md = `# Adoption checklist\n\nGenerated by vera-design-adopt/checklist.mjs. Every must-keep item from Notes/39–40 with where the design shows it. A row that is not shown is still KEPT unless the user says otherwise; a dropped row goes to Note 41 §5 (parked) with the user's word.\n\n| source | must-keep item | status |\n|---|---|---|\n${rows.join('\n')}\n\n${rows.length} rows · ${rows.filter((r) => r.includes('NOT SHOWN')).length} not shown in any board.\n`;
fs.writeFileSync(OUT, md);
console.log(rows.length + ' rows → ' + OUT);
